kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-local-bamboo-agent-build-dir-cache
  namespace: confluence
  labels:
    app: bamboo
    type: local
spec:
  storageClassName: ceph-block
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: confluence
    name: pvc-local-bamboo-agent-build-dir-cache
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-local-bamboo-agent-build-dir-cache
  namespace: confluence
  labels:
    app: bamboo
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi