kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-bamboo-agent-di-mvn-cache
  namespace: confluence
  labels:
    app: bamboo
    type: local
spec:
  storageClassName: ceph-block
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: confluence
    name: pvc-bamboo-agent-di-mvn-cache

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-bamboo-agent-di-mvn-cache
  namespace: confluence
  labels:
    app: bamboo
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi